AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Content Analysis - Deploys the AWS Content Analysis Application and the required Media Insights Engine Framework

Parameters:
  MieVersion:
    Type: String
    Description: The version of the Media Insights Engine framework to deploy
    Default: "isolated"
    AllowedValues: ["isolated"]
  AdminEmail:
    Description: Email address of the Content Analysis Administrator
    Type: String
  ElasticSearchNodeSize:
    Description: "The node type to be provisioned for the Elasticsearch cluster"
    Type: String
    Default: "t2.small.elasticsearch"
    AllowedValues:
      - "t2.small.elasticsearch"
      - "m4.large.elasticsearch"
      - "m4.xlarge.elasticsearch"
      - "c4.large.elasticsearch"
      - "c4.xlarge.elasticsearch"
      - "r4.large.elasticsearch"
      - "r4.xlarge.elasticsearch"
  DeployTestWorkflow:
    Description: Deploy test workflow which contains operator, stage, and workflow stubs for integration testing
    Type: String
    Default: No
    AllowedValues:
      - Yes
      - No

Mappings:
  ContentAnalysisApp:
    SourceCode:
      S3Bucket: "%%BUCKET_NAME%%"
      CodeKeyPrefix: "content-analysis-solution/%%VERSION%%/code"
      TemplateKeyPrefix: "content-analysis-solution/%%VERSION%%/cf"
      WebsitePrefix: "content-analysis-solution/%%VERSION%%/code/website"

#      S3Bucket:  "mas-build-test-us-west-2"
#      #CodeKeyPrefix: "media-insights-solution/frontend/code"
#      TemplateKeyPrefix: "media-insights-solution/frontend/cf"
#      WebsitePrefix: "media-insights-solution/frontend/code/website"

Resources:
  # Deploy MIE Framework

  MediaInsightsFrameworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - "mas-build-test-us-west-2"
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - "media-insights-solution/"
          - !Ref MieVersion
          - "/cf"
          - "/media-insights-stack.template"
      Parameters:
        DeployTestWorkflow: !Ref DeployTestWorkflow

  # Deploy Elasticsearch

  ContentAnalysisElasticsearchStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-elasticsearch.template"
      Parameters:
        AnalyticsStreamArn: !GetAtt MediaInsightsFrameworkStack.Outputs.AnalyticsStreamArn
        MieDataplaneBucket: !GetAtt MediaInsightsFrameworkStack.Outputs.DataplaneBucket

  # Deploy Auth stack

  ContentAnalysisAuthStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-auth.template"
      Parameters:
        AdminEmail: !Ref AdminEmail
        WorkflowAPIRestID: !GetAtt MediaInsightsFrameworkStack.Outputs.WorkflowApiRestID
        DataplaneAPIRestID: !GetAtt MediaInsightsFrameworkStack.Outputs.DataplaneApiRestID
        ElasticDomainArn: !GetAtt ContentAnalysisElasticsearchStack.Outputs.DomainArn
        DataplaneBucket: !GetAtt MediaInsightsFrameworkStack.Outputs.DataplaneBucket

  ContentAnalysisWebStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: StringFunctions
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-web.template"
      Parameters:
        DataplaneEndpoint: !GetAtt MediaInsightsFrameworkStack.Outputs.DataplaneApiEndpoint
        WorkflowEndpoint: !GetAtt MediaInsightsFrameworkStack.Outputs.WorkflowApiEndpoint
        ElasticEndpoint: !GetAtt ContentAnalysisElasticsearchStack.Outputs.ElasticEndpoint
        DataplaneBucket: !GetAtt MediaInsightsFrameworkStack.Outputs.DataplaneBucket
        UserPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolId
        IdentityPoolId: !GetAtt ContentAnalysisAuthStack.Outputs.IdentityPoolId
        PoolClientId: !GetAtt ContentAnalysisAuthStack.Outputs.UserPoolClientId

  # Deploy workflow

  KitchenSinkWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-analysis-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::GetAtt:
            - MediaInsightsFrameworkStack
            - Outputs.WorkflowCustomResourceArn
        OperatorLibraryStack:
          Fn::GetAtt:
            - MediaInsightsFrameworkStack
            - Outputs.OperatorLibraryStack

  # Custom resources

  StringFunctions:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - S3Bucket
          - .s3-
          - !Ref AWS::Region
          - ".amazonaws.com/"
          - !FindInMap
            - ContentAnalysisApp
            - SourceCode
            - TemplateKeyPrefix
          - "/string.template"

Outputs:
  ContentAnalyisSolution:
    Value: !GetAtt ContentAnalysisWebStack.Outputs.CloudfrontUrl
