AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run update captions"

Parameters:
  GITHUBSHA:
    Type: "String"
    Description: "SHA of GitHub Commit"
  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String

Resources:
  # Stages

  WebCaptionsStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "WebCaptionsStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebCaptions"
  CreateTimeSeriesStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: "CreateTimeSeriesStage"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToSRTCaptions"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToVTTCaptions"

  # Workflow

  UpdateCaptionsWorkflow:
    DependsOn:
      - WebCaptionsStage
      - CreateTimeSeriesStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: "UpdateCaptionsWorkflow"
      StartAt: !GetAtt WebCaptionsStage.name
      Stages: !Sub
        - |-
          {
            "${WebCaptionsStage}":{
              "Next": "${CreateTimeSeriesStage}"
              },
            "${CreateTimeSeriesStage}":{
              "End": true
              }
          }
        - {
          WebCaptionsStage: !GetAtt WebCaptionsStage.Name,
          CreateTimeSeriesStage: !GetAtt CreateTimeSeriesStage.Name
        }
