AWSTemplateFormatVersion: "2010-09-09"
Description: "Media Insights Engine - S3 Consumer stack"

Parameters:
  GITHUBSHA:
    Type: "String"
    Description: "SHA of GitHub Commit"
    Default: ""
  AnalyticsStreamArn:
    Description: "Arn of the MIE kinesis data stream"
    Type: String
  AnalyticsS3Bucket:
    Description: "Arn of the Analytics S3 bucket"
    Type: String

Resources:
  # kinesis s3 firehose

  MetadataFirehoseS3Stream:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamName: !Sub "${AWS::StackName}-stream-s3"
      DeliveryStreamType: KinesisStreamAsSource
      S3DestinationConfiguration:
        BucketARN: !Ref AnalyticsS3Bucket
        CloudWatchLoggingOptions:
          Enabled: False
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 20
        CompressionFormat: "UNCOMPRESSED"
        Prefix: "analytics/"
        RoleARN: !GetAtt S3FirehoseRole.Arn
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !Ref AnalyticsStreamArn
        RoleARN: !GetAtt S3FirehoseRole.Arn

  S3FirehoseRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${AWS::AccountId}
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-S3FireHosePolicy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "kinesis:DescribeStream"
                  - "kinesis:GetShardIterator"
                  - "kinesis:GetRecords"
                Resource: !Ref AnalyticsStreamArn
              # TODO: Security - Scope this down
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Join ["", [!Ref AnalyticsS3Bucket, "/analytics"]]
                  - !Join ["", [!Ref AnalyticsS3Bucket, "/analytics/*"]]